### ISSUE TITLE
Добавить удобную систему сборки

### ISSUE THREAD

**Issue by BlitGaming** [invizex/SpaceAdventure#1]
Я юзаю Arch Linux на десктопе, мне бы хотелось иметь хотя бы Makefile, чтобы легко компилировать и устанавливать проект.
Чекни мой репозиторий ReactGame, там есть пример простого Makefile

Ну а если ты сам юзаешь Arch, можешь сразу PKGBUILD пакет запилить)

P.S Игра кстати очень сложная, корабль погибает при столкновении со звездной, скорость и количество звёзд слишком большое. Снизь количество и немного скорость, чтобы было играбельно.

**Comment by invizex** [comment]
Проблему заметил поздно, но по поводу сложности игры и Makefile. то в скором времени исправлю и возможно найду применение игровым деньгам чтобы в игре было больше интереса
